common: &common
  adapter: postgresql
  username: gogetix
  password: password # from psql setup, see Postgresql

development:
  <<: *common
  database: gogetix_development

test: &test
  <<: *common
  database: gogetix_test

staging:
  <<: *common
  database: gogetix_staging

production:
  <<: *common
  database: gogetix_production

cucumber:
  <<: *test