common: &common
  adapter: postgresql
  username: gogetix
  password: gogetix # from psql setup, see Postgresql

development:
  <<: *common
  database: gogetix_development

test: &test
  <<: *common
  database: gogetix_test

production:
  <<: *common
  database: gogetix_production

cucumber:
  <<: *test